### PR TITLE
Delete custom style for mobile usability

### PR DESCRIPTION
**Pull request by doehyunbaek**
Hi, really appreciate your great YouTube channel. Wish there was an issue tab but there was not so I report a bug here. The website looks great on desktop but it looks kinda borderline unreadable in mobile devices.  Removing the custom css doesn't look great but at least helps a little in usability.

Below is a screenshot after the change.

image

Just wanted to report this issue and don't mind you closing it. Really love the channel, bye.

### CODE REVIEW

**Comment by doehyunbaek** [comment]
image

This is how It currently looks on my iPhone 12 mini

**Comment by jonhoo** [comment]
Yep, I only very recently started working on the site for the book, so this is on my to-do list still! I'll close this since the fix will be a bit more involved, but know that I'm working on it :)

**Comment by jonhoo** [comment]
Give it a try now? It should be much better :+1:

**Comment by doehyunbaek** [comment]
Looks great now!

**Pull request closed without merging**
