### PR TITLE
Add errata print01-ch07-lst2-open-paren

### PR DESCRIPTION
**Pull request by nmarley**

### CODE REVIEW

**Comment by jonhoo** [comment]
Good catch! I'd actually like the fix to be the the other way though — we should change the _closing_ paren to a brace `}`. Macros can be called with either, and this is less like an argument list than a block, so `{}` feels more appropriate.

**Comment by nmarley** [comment]
Thanks, I had no idea! I will push a commit to use a brace instead.

**Comment by jonhoo** [comment]
I _believe_ the `;` is still needed. I think you need one to terminate all function-like macro invocations :thinking: 

Also, would you mind updating the file name?

**Comment by nmarley** [comment]
No problem updating the filename.

Regarding the semicolon, I got an error when trying it with a brace + semicolon during my own testing. Would you be able to double-check? If you insist I can remove it.

Here is the error I got:

```
error: expected item, found `;`
  --> test2.rs:21:53
   |
21 | test_battery! {u8 as u8_tests3, u128 as u128_tests3};
   |                                                     ^ help: remove this semicolon

error: aborting due to previous error
```

Here is my code if it helps:

https://gist.github.com/nmarley/0831cf27ca12ce7e6b1234af8162e94e

**Comment by nmarley** [comment]
It seems like `println!` works with braces both with and without the `;`, so I'll just assume there's some magic that I don't yet understand and add the semicolon here.

**Comment by jonhoo** [comment]
Huh, no, looks like you're spot on. From [the reference](https://doc.rust-lang.org/nightly/reference/macros.html), macro invocations with a `{}` are not `;`-terminated:
```
MacroInvocationSemi :
      SimplePath ! ( TokenTree* ) ;
   | SimplePath ! [ TokenTree* ] ;
   | SimplePath ! { TokenTree* }
```

This is also supported by https://github.com/rust-lang/rust/issues/34418.

So let's get rid of the `;` again then!

**Comment by nmarley** [comment]
Oh nice! Thanks for letting me know where to find this information.

**Review by jonhoo — APPROVED** [review]
Thanks!

**Pull request merged**
