### PR TITLE
Errata print01-ch11-niche-ffi

### PR DESCRIPTION
**Pull request by monoid**
I don't quite understand your wording and what is the intended correct variant, so it is just a starting point.

### CODE REVIEW

**Comment by jonhoo** [comment]
Ah, yes, that should be using `NonNull<T>` instead of `*mut T`! Would you mind updating the errata PR to reflect that?

**Comment by monoid** [comment]
Sure, updated!

**Review by jonhoo — APPROVED** [review]
Thanks!

**Comment by monoid** [comment]
@jonhoo Thank you for the all great work!  My best wishes for 2022 (it has already arrived in my timezone).

**Pull request merged**
